apiVersion: v1
name: kdr-masterreplica
description: A Helm chart for deplying a master and replica MariaDB Database installation
home: http://github.com/kesterriley/my-helm-charts
maintainers:
  - name: kesterriley
    email: kesterriley@hotmail.com
    url: https://github.com/kesterriley
version: 0.1.26
appVersion: 1.16.5
