apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdr-galera.fullname" . }}-0
  #namespace: kdr-galera
  labels:
    name: {{ template "kdr-galera.fullname" . }}-0
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 3309
    name: recovery
  - port: 4444
    name: sst
  - port: 4567
    name: gcom
  - port: 4568
    name: gcom2
  - port: 8080
    name: hup
  - port: 8081
    name: hboot
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "kdr-galera.fullname" . }}-0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdr-galera.fullname" . }}-1
  #namespace: kdr-galera
  labels:
    name: {{ template "kdr-galera.fullname" . }}-1
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 3309
    name: recovery
  - port: 4444
    name: sst
  - port: 4567
    name: gcom
  - port: 4568
    name: gcom2
  - port: 8080
    name: hup
  - port: 8081
    name: hboot
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "kdr-galera.fullname" . }}-1
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "kdr-galera.fullname" . }}-2
  #namespace: kdr-galera
  labels:
    name: {{ template "kdr-galera.fullname" . }}-2
spec:
  ports:
  - port: 3306
    name: mysql
  - port: 3309
    name: recovery
  - port: 4444
    name: sst
  - port: 4567
    name: gcom
  - port: 4568
    name: gcom2
  - port: 8080
    name: hup
  - port: 8081
    name: hboot
  type: ClusterIP
  selector:
    statefulset.kubernetes.io/pod-name: {{ template "kdr-galera.fullname" . }}-2
