{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kdr-galera.serviceAccountName" . }}
  labels:
{{ include "kdr-galera.labels" . | nindent 4 }}
{{- end -}}
