version: 2
jobs:
  release-charts:
    steps:
      - run:
          command: |
            echo "doing nothing"
workflows:
  version: 2
  release:
    jobs:
      - release-charts:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master
