apiVersion: v1
name: kdr-galera
description: A Helm chart for creating MariaDB Galera Cluster with MaxScale
home: http://github.com/kesterriley/my-helm-charts
maintainers:
  - name: kesterriley
    email: kesterriley@hotmail.com
    url: https://github.com/kesterriley
version: 0.1.44
appVersion: 1.16.7
